In [1]:
!git clone https://github.com/suhas2071/datafiles.git

Cloning into 'datafiles'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 97 (delta 25), reused 54 (delta 12), pack-reused 3
Receiving objects: 100% (97/97), 15.22 MiB | 12.28 MiB/s, done.
Resolving deltas: 100% (25/25), done.


In [2]:
import pandas as pd
import numpy as np
dataset = pd.read_csv('/content/datafiles/diabetes.csv')
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             74             23      112  26.2   
766            1      126              0              0        0  30.1   
767            1      128             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [3]:
dataset.shape

(768, 9)

In [4]:
dataset[['Age','Outcome']].corr()

Age   Outcome
Age      1.000000  0.238356
Outcome  0.238356  1.000000

In [5]:
dataset[['Glucose','Outcome']].corr()

Glucose   Outcome
Glucose  1.000000  0.465754
Outcome  0.465754  1.000000

In [6]:
dataset[['BMI','Outcome']].corr()

BMI   Outcome
BMI      1.000000  0.292695
Outcome  0.292695  1.000000

In [ ]:
BloodPressure

In [7]:
dataset[['BloodPressure','Outcome']].corr()

BloodPressure   Outcome
BloodPressure       1.000000  0.058972
Outcome             0.058972  1.000000

In [8]:
dataset.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
X = dataset.drop('Outcome', axis=1)
X


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             74             23      112  26.2   
766            1      126              0              0        0  30.1   
767            1      128             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [10]:
y = dataset['Outcome']
y


0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43,stratify=y)



In [41]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
305            2      120             76             37      105  39.7   
49             7      105              0              0        0   0.0   
676            9      156             86              0        0  24.8   
333           12      106             80              0        0  23.6   
336            0      117              0              0        0  33.8   
..           ...      ...            ...            ...      ...   ...   
29             5      117             92              0        0  34.1   
322            0      124             70             20        0  27.4   
526            1       97             64             19       82  18.2   
295            6      151             62             31      120  35.5   
75             1        0             48             20        0  24.7   

     DiabetesPedigreeFunction  Age  
305                     0.215   29  
49                      0.305   24  
676                     0.230   53  
333                     0.137   44  
336                     0.932   44  
..                        ...  ...  
29                      0.337   38  
322                     0.254   36  
526                     0.299   21  
295                     0.692   28  
75                      0.140   22  

[614 rows x 8 columns]

In [13]:
y_train

497    0
520    0
236    1
141    0
727    0
      ..
16     1
58     0
277    0
255    1
320    0
Name: Outcome, Length: 614, dtype: int64

In [42]:
#from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
#from sklearn.tree import DecisionTreeClassifier

#classifier = DecisionTreeClassifier(criterion='entropy')

classifier = RandomForestClassifier(n_estimators=350,criterion='entropy',max_depth=10)
classifier.fit(X_train, y_train)


RandomForestClassifier(criterion='entropy', max_depth=10, n_estimators=350)

In [15]:
X_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
557            8      110             76              0        0  27.8   
383            1       90             62             18       59  25.1   
680            2       56             56             28       45  24.2   
205            5      111             72             28        0  23.9   
188            8      109             76             39      114  27.9   
..           ...      ...            ...            ...      ...   ...   
344            8       95             72              0        0  36.8   
470            1      144             82             40        0  41.3   
245            9      184             85             15        0  30.0   
645            2      157             74             35      440  39.4   
102            0      125             96              0        0  22.5   

     DiabetesPedigreeFunction  Age  
557                     0.237   58  
383                     1.268   25  
680                     0.332   22  
205                     0.407   27  
188                     0.640   31  
..                        ...  ...  
344                     0.485   57  
470                     0.607   28  
245                     1.213   49  
645                     0.134   30  
102                     0.262   21  

[154 rows x 8 columns]

In [43]:
y_pred = classifier.predict(X_test)

In [17]:
y_pred

array([1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0])

In [18]:
y_test

557    0
383    0
680    0
205    0
188    1
      ..
344    0
470    0
245    1
645    0
102    0
Name: Outcome, Length: 154, dtype: int64

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0])

In [44]:
# comparing actual response values (y_test) with predicted response values (y_pred)
from sklearn import metrics

print(" model accuracy:", metrics.accuracy_score(y_test, y_pred))

 model accuracy: 0.7987012987012987


In [ ]:
2%

In [45]:
import pickle
with open("model.pkl",'wb') as model_pkl:
    pickle.dump(classifier,model_pkl)

In [46]:
import pickle
with open('/content/model.pkl','rb') as model_file:
    model_suhas=pickle.load(model_file)

In [47]:
# making prediction for out of sample data
sample = [[6,148,72,35,0,33.6,0.627,50]]
preds = model_suhas.predict(sample)
print(preds)

[1]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
classifier.score(X_test, y_test)

0.7142857142857143

In [ ]:
classifier.score(X_train, y_train)

1.0

In [ ]:
Its means overfitting
You should:
1.Always split the data and try to achieve high accuracy on the test set rather than the training set.
2.If your training data accuracy is quite higher than the test data this means your modell is overfitting.

Your model is overfitting to your training data.
You need to try to tune the hyperpharameters so it will get a good accuracy when the you split the data.
Otherwise model is not that useful.

In [ ]:


sample=[[1,189,60,23,846,30.1,0.398,59]]

preds= classifier.predict(sample)
print("Predictions:", preds)

Predictions: [1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
from sklearn.metrics import f1_score

#y_pred_class = y_pred_pos > threshold
f1_score(y_test, y_pred)

0.5849056603773585

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[79, 21],
       [23, 31]])

In [ ]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)

0.5740740740740741

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

0.5961538461538461

In [ ]:
treshhold =

1
0
0.6
44% - 0
56% - 0
72% - 1
32% - 0



In [ ]:

sample=[[1,85,66,29,0,26.6,0.351,31]]

preds= classifier.predict(sample)
print("Predictions:", preds)

Predictions: [0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"
