In [1]:
from numpy import array
import numpy as np
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values=np.array(data)
#values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']
[0 0 2 0 1 1 2 0 2 1]


In [ ]:
myinverse_encoding=label_encoder.inverse_transform([0, 0, 2, 0, 1, 1, 2, 0, 2, 1])
myinverse_encoding

array(['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold',
       'warm', 'hot'], dtype='<U4')

In [ ]:

# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded_new = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded_new)
print(onehot_encoded)


[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [ ]:
mydata = ['Mumbai', 'Pune', 'Bengaluru', 'Chennai',"Mumbai","Pune"]

mycity=np.array(mydata)

label_encoder = LabelEncoder()
integer_encoded_city = label_encoder.fit_transform(mycity)
print(integer_encoded_city)


[2 3 0 1 2 3]


In [ ]:
inverse_encoding_city=label_encoder.inverse_transform([2, 3, 0, 1, 2, 3])
inverse_encoding_city

array(['Mumbai', 'Pune', 'Bengaluru', 'Chennai', 'Mumbai', 'Pune'],
      dtype='<U9')

In [ ]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
#integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
integer_encoded_city = integer_encoded_city.reshape(-1, 1)
#It expect 2D data
print(integer_encoded_city)
onehot_encoded_city = onehot_encoder.fit_transform(integer_encoded_city)
print(onehot_encoded_city)

[[2]
 [3]
 [0]
 [1]
 [2]
 [3]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
# preprocessing is a module
# LabelEncoder is a Class
le = LabelEncoder()
le.fit([1,2,2,2,5,5,6])
le.classes_

array([1, 2, 5, 6])

In [ ]:
from numpy import array
import numpy as np
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
values=np.array(data)
#values = array(data)
print(values)

['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']


In [ ]:
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[0 0 2 0 1 1 2 0 2 1]


In [ ]:
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
#integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
integer_encoded = integer_encoded.reshape(-1, 1)
#It expect 2D data
print(integer_encoded)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [2]
 [0]
 [2]
 [1]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


# https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/

In [ ]:
from numpy import array
from numpy import argmax
from keras.utils import to_categorical
# define example
data = [1, 3, 2, 0, 3, 2, 2, 1, 0, 1]
data = array(data)
print(data)
# one hot encode
encoded = to_categorical(data)
print(encoded)
# invert encoding
inverted = argmax(encoded[5])
print(inverted)

[1 3 2 0 3 2 2 1 0 1]
[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
2
